# Before running the build, Travis CI installs dependencies:
# mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
# mvnw wrapper: ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

# pom.xml Travis CI builds your project with Maven 3
# mvn test -B
# mvnw wrapper: ./mvnw test -B
language: java

jdk:
  - oraclejdk11
  - openjdk8
  - openjdk10
  - openjdk11

before_install: skip
install: skip

before_script:
  - mvn test
script: skip
after_script: skip

before_cache: skip
after_success: skip
after_failure: skip
